### ISSUE TITLE
Running ./configure fails on CentOS release 6.10

### ISSUE THREAD

**Issue by rodolfojcj** [nils-ohlmeier/sipsak#49]
When I run the "./configure" command on CentOS 6.10, gcc (GCC) 4.4.7 20120313 (Red Hat 4.4.7-23) I got this error:

    checking for getdomainname... yes
    checking for getopt_long... yes
    checking for inet_ntop... yes
    checking for strncasecmp... yes
    checking for strcasestr... yes
    checking for syslog... yes
    checking for pkg-config... /usr/bin/pkg-config
    checking pkg-config is at least version 0.9.0... yes
    checking for CHECK... ./configure: line 6273: syntax error near unexpected token `else'
    ./configure: line 6273: `else'

This is part of the relevant content of the `configure` file, with numbered lines:

    1  #! /bin/sh
    2  # Guess values for system-dependent variables and create Makefiles.
    3  # Generated by GNU Autoconf 2.63 for sipsak 0.9.7pre.
    4  #
    ...
    ...
    6250  
    6251  if test $pkg_failed = yes; then
    6252  
    6253  if $PKG_CONFIG --atleast-pkgconfig-version 0.20; then
    6254          _pkg_short_errors_supported=yes
    6255  else
    6256          _pkg_short_errors_supported=no
    6257  fi
    6258          if test $_pkg_short_errors_supported = yes; then
    6259                  CHECK_PKG_ERRORS=`$PKG_CONFIG --short-errors --print-errors "check >= 0.9.3" 2>&1`
    6260          else
    6261                  CHECK_PKG_ERRORS=`$PKG_CONFIG --print-errors "check >= 0.9.3" 2>&1`
    6262          fi
    6263          # Put the nasty error message in config.log where it belongs
    6264          echo "$CHECK_PKG_ERRORS" >&5
    6265  
    6266          { $as_echo "$as_me:$LINENO: result: no" >&5
    6267  $as_echo "no" >&6; }
    6268  
    6269  
    6270  elif test $pkg_failed = untried; then
    6271  
    6272  
    6273  else
    6274          CHECK_CFLAGS=$pkg_cv_CHECK_CFLAGS
    6275          CHECK_LIBS=$pkg_cv_CHECK_LIBS
    6276          { $as_echo "$as_me:$LINENO: result: yes" >&5
    6277  $as_echo "yes" >&6; }
    6278

If I manually add a no-op statement in line 6271, then the same failure happens at line 7409, being these the relevant lines:

    7386  
    7387  if test $pkg_failed = yes; then
    7388  
    7389  if $PKG_CONFIG --atleast-pkgconfig-version 0.20; then
    7390          _pkg_short_errors_supported=yes
    7391  else
    7392          _pkg_short_errors_supported=no
    7393  fi
    7394          if test $_pkg_short_errors_supported = yes; then
    7395                  GNUTLS319_PKG_ERRORS=`$PKG_CONFIG --short-errors --print-errors "gnutls >= 3.1.9" 2>&1`
    7396          else
    7397                  GNUTLS319_PKG_ERRORS=`$PKG_CONFIG --print-errors "gnutls >= 3.1.9" 2>&1`
    7398          fi
    7399          # Put the nasty error message in config.log where it belongs
    7400          echo "$GNUTLS319_PKG_ERRORS" >&5
    7401  
    7402          { $as_echo "$as_me:$LINENO: result: no" >&5
    7403  $as_echo "no" >&6; }
    7404  
    7405  
    7406  elif test $pkg_failed = untried; then
    7407  
    7408  
    7409  else
    7410          GNUTLS319_CFLAGS=$pkg_cv_GNUTLS319_CFLAGS
    7411          GNUTLS319_LIBS=$pkg_cv_GNUTLS319_LIBS
    7412          { $as_echo "$as_me:$LINENO: result: yes" >&5
    7413  $as_echo "yes" >&6; }
    7414  
    7415  
    7416  cat >>confdefs.h <<\_ACEOF
    7417  #define HAVE_GNUTLS_319 1
    7418  _ACEOF
    7419  
    7420  
    7421  fi
    7422  
    7423

What is the reason of this failure?
How can it be solved?

Thanks in advance.

**Comment by nils-ohlmeier** [comment]
I'm assuming you generated the configure locally. What versions of autoconf, automake and libtool did you use?
I have to admit that I don't understand what the failure is about.

**Comment by rodolfojcj** [comment]
I was trying to follow the installation steps of the REAME file.

First I ran `autoreconf --install`, which gave this output:

    configure.ac:23: installing `./config.guess'
    configure.ac:23: installing `./config.sub'
    configure.ac:6: installing `./install-sh'
    configure.ac:6: installing `./missing'
    Makefile.am: installing `./INSTALL'
    Makefile.am:7: compiling `src/transport.c' in subdir requires `AM_PROG_CC_C_O' in `configure.ac'
    Makefile.am: installing `./depcomp'
    Makefile.am:27: variable `FAKE_TRANSPORT_SOURCES' is defined but no program or
    Makefile.am:27: library has `FAKE_TRANSPORT' as canonical name (possible typo)

Next I ran `./configure` which gave the output I originally reported that shows this message:

    ./configure: line 6273: `else'

The versions of the packages you are asking for are these:

    autoconf-2.63-5.1.el6.noarch
    automake-1.11.1-4.el6.noarch
    libtool-ltdl-2.2.6-15.5.el6.x86_64
    libtool-ltdl-devel-2.2.6-15.5.el6.x86_64
    libtool-2.2.6-15.5.el6.x86_64

Just for reference I'm attaching [the list of installed packages on the system](https://github.com/nils-ohlmeier/sipsak/files/2705166/centos6_installed_packages_22dec2018.txt), which is CentOS 6.10 running 64 bits Linux kernel 4.18.16.

Thank you!

**Comment by nils-ohlmeier** [comment]
I was able to reproduce this in a VM with CentOS 6.10.
Looks like the old pkg-config in CentOS 6.10 can't hand handle the fail branch being [], but using : instead works. Fix coming up.
