### ISSUE TITLE
Official Upstream?

### ISSUE THREAD

**Issue by oxr463** [nils-ohlmeier/sipsak#58]
Greetings,

Is this the official upstream for this project?

If so, it might be helpful to include that the project has moved to github,
from the previous sourceforge ref, (https://sourceforge.net/projects/sipsak.berlios).

**Comment by nils-ohlmeier** [comment]
Yes I'm the author of sipsak. And I'm trying to make this the official upstream project (although sipsak appears to have branched (or forked) over multiple GitHub repos over the years).

I'll give it a try to update the sourceforge page.

**Comment by oxr463** [comment]
Thank you. There do indeed seem to be many forks, and many distribution packages still reference the source forge, so I wasn't sure if this too was also a fork.

**Comment by nils-ohlmeier** [comment]
Hmm I don't see a way to take over the existing project sipsak.berlios. I guess the berliosrobot would have to give admin rights to me. Which might be hard, as berlios is dead.

**Comment by nils-ohlmeier** [comment]
I messaged the berliosrobot via sourceforge. Lets wait and see if any human still answers on that account.

**Comment by nils-ohlmeier** [comment]
Wow got added as project admin in less then a day.
Pointed the website to here. And also put a note in the description pointing to here.

Thanks for kicking this off @oxr463

**Comment by oxr463** [comment]
Awesome!
