### ISSUE TITLE
Buidling TLS fails because libgnutls-config is no longer used

### ISSUE THREAD

**Issue by rodmur** [nils-ohlmeier/sipsak#7]
sipsak's configure keeps trying to use libgnutls-config which has been replaced by pkg-config.  I'll try to get around to making a patch, but I figured I should report this in case someone can fix it quicker.

**Comment by nils-ohlmeier** [comment]
Thanks for the report.
Looks to me like the right "solution" is probably to remove the whole gnutls section in 'acinclude.m4' and replace it with something more recent. I'll try to have a look at it this week.

**Comment by nils-ohlmeier** [comment]
I believe the GnuTLS update from two days ago should fix this.
